### ISSUE TITLE
Will Notebook Save Logs to CloudWatch?

### ISSUE THREAD

**Issue by knoam** [aws-samples/sagemaker-run-notebook#11]
According to the [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/logging-cloudwatch.html), it doesn't sound like Notebook Instance logging goes to CloudWatch: "anything an algorithm container, a model container, or a notebook instance lifecycle configuration sends to stdout or stderr is also sent to Amazon CloudWatch Logs." Is that correct? In that case, how can we get the logs from running a Notebook go to CloudWatch?

In addition, what's the best practice for going from a notebook to a scheduled, logging execution, while this library is still experimental?

**Comment by tomfaulhaber** [comment]
Notebook instance logging doesn't go to Cloudwatch so far as I know (if I remember correctly it's logged locally on the instance and you can look there).

However, this package doesn't use notebook instances, it uses SageMaker processing jobs which do log their stdout/err to Cloudwatch into the group `/aws/sagemaker/ProcessingJobs` with a stream name like: `papermill-powers-2020-11-07-00-49-42/algo-1-1604710358`, the pattern being `papermill-<notebook>-YYYY-MM-DD-hh-mm-ss/algo-1-<random>`. 

Note: What's logged is the output that written to stdout of the papermill run. To get the code in your notebook to send code to the logs this way, use the file descriptor `sys.__stdout__` in something like `print("hello, world!", file=sys.__stdout__)` or whatever.

Regular notebook output goes into the notebook that's being created and can be retrieved by using the `run-notebook download` command. 

This package is experimental, but it represents our idea of the best approach to doing this currently. If you don't want to depend on the library/CLI/UX provided here, you can use the do it yourself recipe described in [DIY.md][DIY] to achieve the same effect using only raw AWS commands and some supplied CloudFormation which you can modify to taste.

[DIY]: https://github.com/aws-samples/sagemaker-run-notebook/blob/master/DIY.md
