### ISSUE TITLE
Getting Error Message while creating container

### ISSUE THREAD

**Issue by rajmatiGM** [aws-samples/sagemaker-run-notebook#12]
Command : 

!run-notebook create-container
botocore.errorfactory.InvalidInputException: An error occurred (InvalidInputException) when calling the CreateProject operation: CodeBuild is not authorized to perform: sts:AssumeRole on arn:aws:iam::<ACCOUNT>:role/ExecuteNotebookCodeBuildRole-<Region>

While trying to !run-notebook create-infrastructure ( without update  even on a new sagemaker notebook instance) 
The infrastructure has already been created. Use update to update it.

When I do it with update 

 !run-notebook create-infrastructure --update it complains
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the UpdateStack operation: Stack:arn:aws:cloudformation:us-east-1:<ACCOUNT>:stack/sagemaker-run-notebook/<ID> is in ROLLBACK_COMPLETE state and can not be updated.

Please suggest what am I missing.

**Comment by rajmatiGM** [comment]
As suggested , deleted the stack , and used the right permissions to rerun the create-infrastructure and was able to successfully run it.

**Comment by aks-0389** [comment]
@rajmatiGM -I am facing a similar issue. Please share the permissions you have used

**Comment by rajmatiGM** [comment]
@aks-0389 , just temporarily attach the admin permissions , run the commands for once and on success remove the admin privileges. That is how I could proceed finally.
