### ISSUE TITLE
run-notebook create-container  - toomanyrequests 

### ISSUE THREAD

**Issue by simonprudhomme** [aws-samples/sagemaker-run-notebook#22]
Hi, 

When creating the docker image with `run-notebook create-container`, I received this error message. 
What can I do ? 

```
[Container] 2021/07/14 21:13:37 Running command docker pull -q ${BASE_IMAGE}
Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
```

**Comment by simonprudhomme** [comment]
Solved.
I just had to create a Docker Account and log in (on Docker Desktop with MacOS)

**Comment by fjpa121197** [comment]
Hi @simonprudhomme, how did you solve this? I'm currently running this tool in sagemaker studio. So not really sure how can I login to my docker account from it.
