### ISSUE TITLE
start.sh lifecycle configuration issue with 'initctl'

### ISSUE THREAD

**Issue by martin-kociemba** [aws-samples/sagemaker-run-notebook#57]
I am using Jupyterlab3 in a Sagemaker notebook instance.

Using the start.sh information to amend the lifecycle script and I am getting the following error message in the cloudwatch logs:
`/tmp/OnStart_2022-08-11-14-58486lgb20: line 54: initctl: command not found`

On a sidenote, the command using `source /home/ec2-user/anaconda3/bin/deactivate` seems to be outdated, since the log also return the following message:
`DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'. `

The latter is related to due to the change in conda 4.6, maybe the prior has something to do with it as well?
The change is described here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html

**Comment by tomfaulhaber** [comment]
Will be fixed when we release JupyerLab 3 support

**Comment by tomfaulhaber** [comment]
[v0.22.0](https://github.com/aws-samples/sagemaker-run-notebook/releases/tag/v0.22.0) is now released with JupyterLab 3.x support. The new start.sh in this release fixes this issue.
