### ISSUE TITLE
run-notebook command not found after install sagemaker-run-notebook

### ISSUE THREAD

**Issue by DorisDoris01** [aws-samples/sagemaker-run-notebook#59]
Hi all,

I successfully installed sagemaker-run-notebook using the below command
`$ pip3 install https://github.com/aws-samples/sagemaker-run-notebook/releases/download/v0.19.0/sagemaker_run_notebook-0.19.0.tar.gz --user`

but I failed to run the command
```
$ run-notebook create-infrastructure
-bash: run-notebook: command not found
```

Appreciate any comments. Thanks!

**Comment by DorisDoris01** [comment]
I am able to find the path where the package is in and the package is there. But still cannot run the command...

**Comment by DorisDoris01** [comment]
Close as solved!

**Comment by jzilly** [comment]
What helped me was to remove "--user" from the pip install command. Did anyone have a similar experience?
