### ISSUE TITLE
Support china regions

### ISSUE THREAD

**Issue by yosefbs** [aws-samples/sagemaker-run-notebook#60]
A domain for sts endpoint in china regions should be added in this method:

`def _domain_for_region(region):
    return "c2s.ic.gov" if region == "us-iso-east-1" else "amazonaws.com"
`

Also each arn in code colud be also arn:aws-cn:........

**Comment by tomfaulhaber** [comment]
Merged. Will be part of the next release.

**Comment by tomfaulhaber** [comment]
[v0.22.0](https://github.com/aws-samples/sagemaker-run-notebook/releases/tag/v0.22.0) is now released with this fix in it.
